name: test

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Install dependencies
      run: pipenv sync

    - name: Test
      working-directory: ./python
      run: pipenv run python -m unittest discover tests